name: Django CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install system deps (Chromium)
        run: |
          sudo apt-get update
          # en Ubuntu runner, este paquete existe como "chromium-browser";
          # si no, instala "chromium" y "chromium-chromedriver".
          sudo apt-get install -y chromium-browser chromium-chromedriver || \
          sudo apt-get install -y chromium chromium-driver

      - name: Install Python deps (sin requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install "Django==5.2.*" "selenium>=4.20,<5" pytest

      - name: Django checks & migrate
        run: |
          python manage.py check
          python manage.py migrate --noinput

      - name: Run tests (headless) — allow failure
        continue-on-error: true
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings
        run: |
          python manage.py test -v 2
